# Generated by Django 5.2.7 on 2026-01-04 02:32

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poster', '0002_linkedaccounts'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedulepost',
            name='error_log',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='schedulepost',
            name='media_file',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='media'),
        ),
        migrations.AlterField(
            model_name='schedulepost',
            name='id',
            field=models.UUIDField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='schedulepost',
            name='scheduled_time',
            field=models.DateTimeField(db_index=True),
        ),
    ]
