# Generated by Django 5.2.7 on 2026-01-10 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poster', '0003_schedulepost_error_log_schedulepost_media_file_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedulepost',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('SCHEDULED', 'Scheduled'), ('PUBLISHED', 'Published'), ('FAILED', 'Failed'), ('PROCESSING', 'Processing')], default='DRAFT', max_length=10),
        ),
    ]
