# Generated by Django 5.2.7 on 2026-01-11 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poster', '0004_alter_schedulepost_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedulepost',
            name='id',
            field=models.UUIDField(auto_created=True, primary_key=True, serialize=False),
        ),
    ]
