# Generated by Django 5.2.7 on 2026-01-11 03:31

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poster', '0005_alter_schedulepost_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedulepost',
            name='id',
            field=models.UUIDField(default=uuid.uuid8, editable=False, primary_key=True, serialize=False),
        ),
    ]
